# Generated by Django 3.2.8 on 2021-12-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20211218_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='image',
        ),
    ]
