# Generated by Django 3.2.8 on 2021-12-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_remove_vendor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
