# Generated by Django 3.2.8 on 2021-12-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20211219_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
    ]
