# Generated by Django 3.2.8 on 2021-12-19 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20211219_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
